# Generated by Django 5.1.6 on 2026-05-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertytrack', '0002_alter_rental_rent_amount_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
