# Generated by Django 5.1.6 on 2026-06-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertytrack', '0004_inspection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
